Change class component to function and add hooks
Leandro-Barretoo/math__magicians pull request #4
Opened 2021-08-19 22:14 UTC by Leandro-Barretoo

In this PR I change the Calculator class to a functional component and add hooks instead of the class state.
Thank you for the review.

2021-08-19 23:00 UTC, Dipeshtwis requested changes
Hi @pasytchangwa, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Refactored the Calculator component (components/Calculator.js) from a class-based component to a functional component with hooks.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [ ] I can see the project title, description is not matching to the current project. Please update it to make the README professional. Also, add the steps on how to run the project in local like 

```
git clone https://yourrepo.git
cd yourrepo
npm install
npm start
```
- [ ] Currently, the live link is pointing to another site that doesn't exist. please fix it.

**_Also check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-19 23:00 UTC, Dipeshtwis commented on src/components/Calculator.js
> +  };
- [ ] I'm trying to click the first number and I'm getting this error that `obj is null`. Please check the same in the screenshot and try to fix it. I think there is a problem with the `next` state.

![Screenshot from 2021-08-20 04-25-52](https://user-images.githubusercontent.com/22434660/130154731-c8bef3f7-b14f-4a88-9f8f-9278af57bd85.png)

2021-08-20 11:45 UTC, Leandro-Barretoo commented
I fixed the hook and updated the readme file with more descriptive information.

2021-08-20 12:09 UTC, bellom requested changes
## Hi @Leandro-Barretoo  👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 12:09 UTC, bellom commented on README.md
> +[Live Demo Link](https://leandro-barretoo.github.io/math_magicians/build)
Thanks for updating the live link but the link added is pointing to page `404`

![image](https://user-images.githubusercontent.com/31897434/130229527-318bf86f-b554-4112-bf35-d80c587b324f.png)

Kindly fix

2021-08-20 12:09 UTC, bellom commented on src/components/Calculator.js
>    const changeState = (e) => {
Could this be coming from my end 🤦, your app seems not to work properly, it takes 2-3 clicks for a successful click.
i.e I have to click the button 3 times.
And also I can't perform a successful operation like `5+5`, I got the following error 👇 

![image](https://user-images.githubusercontent.com/31897434/130230650-8dafaf7d-fae6-497b-b710-0a009ce980e9.png)

2021-08-20 13:31 UTC, Leandro-Barretoo commented
I deployed the app with gh-pages and updated the live link.
On my end, I don't have the invalid number error, so I cannot fix it.
Thank you for the review.

2021-08-20 14:01 UTC, ZawadiSumba66 approved these changes
Hi @Leandro-Barretoo 👋 , 
## STATUS: APPROVED 👍 
Great job implementing the changes requested by the previous reviewers.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### NOTE:
Kindly correct the live demo link as requested by the other reviewers.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 14:20 UTC, Leandro-Barretoo commented
Fix live link

2021-08-20 14:20 UTC, merged